# Generated by Django 5.0.6 on 2024-05-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyId', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500000)),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='additionalPlotOutline',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='story',
            name='characterName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='inspiration',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='questionToChat',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
