# Generated by Django 5.0.6 on 2024-06-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_storymessage_alter_story_additionalplotoutline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='storyTitle',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
