# Generated by Django 5.0.6 on 2024-06-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_userwallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='amount',
            new_name='balance',
        ),
    ]
