# Generated by Django 5.0.6 on 2024-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0007_rename_amount_userwallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
