# Generated by Django 5.0.6 on 2024-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0008_alter_userwallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='ownerId',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
